name: ecogo_driver
description: ECOGO driver app (MVP) — post rides, manage seats, broadcast GPS, chat.
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ecogo_core:
    path: ../ecogo-core
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  geolocator: ^12.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
