name: ecogo_passenger
description: ECOGO passenger app (MVP) — search, book, track, chat.
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ecogo_core:
    path: ../ecogo-core
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
